# 专用连接池Redis代理配置文件
server:
  port: 6380
  max_connections: 1000
  read_timeout: "30s"
  write_timeout: "30s" 
  idle_timeout: "300s"
  use_gnet: false
  use_affinity: false
  use_goredis: false
  use_goredis_v2: false
  use_goredis_v2_fixed: false
  use_intelligent_pool: false
  use_optimized_affinity: false
  use_dedicated_proxy: true  # 启用专用连接池代理

# 专用连接池配置
dedicated_proxy:
  max_connections: 200      # 最大Redis连接数（增加）
  init_connections: 20      # 初始连接数（增加）
  wait_timeout: "2s"        # 获取连接等待超时（减少，快速失败）
  idle_timeout: "3m"        # 连接空闲超时（减少，更快回收）
  session_timeout: "5m"     # 客户端会话超时（减少）
  command_timeout: "30s"    # Redis命令执行超时（适当放宽，降低高并发下误超时）
  default_database: 0       # 默认数据库
  default_client_name: "redis-proxy-dedicated"  # 默认客户端名称
  stats_interval: "30s"     # 统计报告间隔

# Redis服务器配置
redis:
  host: "localhost"
  port: 6379
  password: ""              # Redis密码（如果有）
  database: 0
  pool_size: 10
  min_idle_connections: 2
  max_idle_connections: 5
  connection_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

# 缓存配置（可选）
cache:
  enabled: true                    # 启用本地缓存
  ttl: "300s"                      # 缓存项生存时间
  enable_ttl: true                 # 启用TTL过期
  eviction_policy: "lru"           # 淘汰策略
  enable_stats: true               # 启用统计信息
  cleanup_interval: "60s"          # 清理间隔
  hard_max_cache_size: 100         # 总缓存大小限制（MB）
  max_entry_size: 1048576          # 单条缓存条目大小限制（字节）- 1MB
  verbose: false                   # 启用BigCache详细日志（调试用）

# Kafka配置（可选）
kafka:
  enabled: false                           # 启用Kafka缓存一致性
  brokers: ["localhost:9092"]             # Kafka代理地址
  topic: "redis-cache-events"             # 缓存事件主题
  group_id: "redis-proxy-group"           # 消费者组ID
  auto_offset_reset: "latest"             # 偏移量重置策略
  session_timeout: "30s"                  # 会话超时
  heartbeat_interval: "3s"                # 心跳间隔

# 监控配置
monitoring:
  enabled: true
  big_key_threshold: "10MB"
  stats_interval: "60s"
  metrics_port: 8080
  health_check_path: "/health"
  metrics_path: "/metrics"
