server:
  port: 6380
  max_connections: 2000
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "120s"
  use_intelligent_pool: true

intelligent_pool:
  max_pool_size: 500          # 增加连接池大小
  min_idle_conns: 50          # 增加最小空闲连接
  max_idle_conns: 400         # 增加最大空闲连接
  idle_timeout: "30s"         # 减少空闲超时
  max_lifetime: "5m"          # 减少连接最大生命周期
  session_timeout: "2m"       # 减少会话超时
  cleanup_interval: "10s"     # 减少清理间隔
  stats_interval: "60s"       # 增加统计间隔
  command_timeout: "2s"       # 减少命令超时
  max_retries: 2              # 减少重试次数
  connection_hold_time: "0s"  # 不保持连接

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
  connection_timeout: "2s"    # 减少连接超时
  read_timeout: "1s"          # 减少读超时
  write_timeout: "1s"         # 减少写超时
  pool_size: 500              # 增加池大小
  min_idle_connections: 50    # 增加最小空闲连接
  max_idle_connections: 400   # 增加最大空闲连接

cache:
  enabled: false              # 关闭缓存减少开销

kafka:
  enabled: false              # 关闭Kafka减少开销

monitoring:
  enabled: false              # 关闭监控减少开销

log:
  level: "error"              # 只记录错误日志
  format: "console"
  output: "stdout"
