server:
  port: 6380
  max_connections: 1000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "300s"
  use_intelligent_pool: true

intelligent_pool:
  max_pool_size: 10
  min_idle_conns: 1
  max_idle_conns: 5
  idle_timeout: "5m"
  max_lifetime: "1h"
  session_timeout: "30m"
  cleanup_interval: "1m"
  stats_interval: "30s"
  command_timeout: "30s"
  max_retries: 3

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
  connection_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

log:
  level: "info"
  format: "console"
  output: "stdout"
