server:
  port: 6380
  max_connections: 1000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "300s"
  use_intelligent_pool: true

intelligent_pool:
  max_pool_size: 200
  min_idle_conns: 20
  max_idle_conns: 200
  idle_timeout: "60s"
  max_lifetime: "10m"
  session_timeout: "5m"
  cleanup_interval: "30s"
  stats_interval: "30s"
  command_timeout: "5s"
  max_retries: 3
  connection_hold_time: "0s"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
  connection_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  pool_size: 200
  min_idle_connections: 20
  max_idle_connections: 200

log:
  level: "info"
  format: "console"
  output: "stdout"
