# Redis Proxy Configuration - go-redis V2 Fixed Mode (Final enhanced version)

server:
  port: 6385  # Use different port to avoid conflict
  max_connections: 1000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "300s"
  use_gnet: false
  use_affinity: false  
  use_goredis: false
  use_goredis_v2: false
  use_goredis_v2_fixed: true  # Enable final enhanced go-redis V2 Fixed mode

# GoRedis V2 Fixed specific configuration
goredis:
  pool_size: 15
  min_idle_conns: 3
  max_conn_age: "2h"
  idle_timeout: "45m"
  dial_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  session_timeout: "2h"
  stats_interval: "30s"

# Redis backend configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 15
  min_idle_connections: 3
  max_idle_connections: 8
  connection_timeout: "10s"
  read_timeout: "8s"
  write_timeout: "8s"

# Pool configuration
pool:
  max_idle: 10
  max_active: 20
  idle_timeout: "300s"
  wait: true

# Logging configuration
log:
  level: "info"
  format: "text"
