# Redis Proxy Demo Configuration File (gnet High-Performance Mode)
# This configuration file contains settings for all major components with gnet enabled

# Server Configuration
server:
  port: 6380                    # Redis proxy listening port
  max_connections: 1000         # Maximum concurrent connections
  read_timeout: "30s"           # Client read timeout
  write_timeout: "30s"          # Client write timeout
  idle_timeout: "300s"          # Connection idle timeout
  use_gnet: true                # Use gnet for high-performance server (ENABLED)

# Redis Server Configuration  
redis:
  host: "localhost"             # Redis server hostname
  port: 6379                    # Redis server port
  password: ""                  # Redis server password (if required)
  database: 0                   # Redis database number
  pool_size: 10                 # Connection pool size
  min_idle_connections: 2       # Minimum idle connections in pool
  max_idle_connections: 5       # Maximum idle connections in pool
  connection_timeout: "5s"      # Redis connection timeout
  read_timeout: "3s"            # Redis read timeout
  write_timeout: "3s"           # Redis write timeout

# Local Cache Configuration
cache:
  enabled: true                 # Enable/disable local caching
  max_size: "256MB"            # Maximum cache size (e.g., 256MB, 1GB)
  ttl: "300s"                  # Default cache TTL (time to live)
  eviction_policy: "lru"       # Cache eviction policy (lru, lfu, fifo)
  cleanup_interval: "60s"      # Cache cleanup interval

# Kafka Configuration (for cache consistency)
kafka:
  enabled: true                 # Enable/disable Kafka integration
  brokers:                      # Kafka broker addresses
    - "localhost:9092"
  topic: "redis-cache-events"   # Topic for cache invalidation events
  group_id: "redis-proxy-group" # Consumer group ID
  auto_offset_reset: "latest"   # Offset reset policy
  session_timeout: "30s"        # Consumer session timeout
  heartbeat_interval: "3s"      # Consumer heartbeat interval

# Monitoring and Statistics Configuration
monitoring:
  enabled: true                 # Enable/disable monitoring
  big_key_threshold: "10MB"     # Threshold for big key detection
  stats_interval: "60s"         # Statistics collection interval
  metrics_port: 8080            # HTTP metrics endpoint port
  health_check_path: "/health"  # Health check endpoint path
  metrics_path: "/metrics"      # Metrics endpoint path

# Logging Configuration
logging:
  level: "info"                 # Log level (debug, info, warn, error)
  format: "json"                # Log format (json, text)
  output: "stdout"              # Log output (stdout, file)
  file_path: "/var/log/redis-proxy.log"  # Log file path (if output=file)
  max_size: "100MB"             # Maximum log file size
  max_backups: 3                # Maximum number of log backups
  max_age: "7d"                 # Maximum age of log files

# Command Filtering Configuration
command_filter:
  enabled: true                 # Enable/disable command filtering
  blacklist:                    # Blacklisted commands (dangerous commands)
    - "FLUSHALL"
    - "FLUSHDB"
    - "KEYS"
    - "DEBUG"
    - "CONFIG"
  whitelist: []                 # Whitelisted commands (empty = allow all except blacklisted)
  
# Performance Tuning
performance:
  buffer_size: "4KB"            # Network buffer size
  worker_pool_size: 100         # Worker goroutine pool size
  max_pipeline_size: 10         # Maximum pipeline request size
