# Redis Proxy Configuration - Connection Affinity Mode
# This configuration enables 1:1 connection mapping between clients and Redis

server:
  port: 6380
  max_connections: 1000
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 300s
  use_gnet: false      # Use traditional server for compatibility
  use_affinity: true   # ✅ Enable connection affinity for WATCH commands

# Connection Affinity Configuration
connection_affinity:
  max_connections: 1000     # Maximum concurrent client connections
  idle_timeout: 5m          # Close idle connections after 5 minutes
  health_check_interval: 30s # Check connection health every 30 seconds
  buffer_size: 32768        # 32KB buffer for data forwarding
  stats_interval: 30s       # Report statistics every 30 seconds

redis:
  host: localhost
  port: 6379
  password: ""              # Redis password (empty for no auth)
  database: 0
  pool_size: 10            # Not used in affinity mode (kept for compatibility)
  min_idle_connections: 2
  max_idle_connections: 5
  connection_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

cache:
  enabled: true
  max_size: 256MB
  ttl: 300s
  eviction_policy: lru
  cleanup_interval: 60s

kafka:
  enabled: true
  brokers:
    - localhost:9092
  topic: redis-cache-events
  group_id: redis-proxy-group
  auto_offset_reset: latest
  session_timeout: 30s
  heartbeat_interval: 3s

monitoring:
  enabled: true
  big_key_threshold: 10MB
  stats_interval: 60s
  metrics_port: 8080
  health_check_path: /health
  metrics_path: /metrics
